name: bq
services:
  appserver:
    type: python:3.7
    build:
      - pip install -r requirements.txt
  database:
    type: postgres:10

env_file:
  - .env

tooling:
  python:
    service: appserver
  pip:
    service: appserver
  psql:
    service: database
    cmd: psql database -h database -U postgres
